services:
  ui:
    image: dpinterview:latest
    environment:
      PGSSLMODE: "disable"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    init: true
    ports: []
  db:
    image: "postgres:17-trixie"
    shm_size: 128mb
    volumes:
      - db:/var/lib/postgresql/data
      - ./schema.16.sql:/docker-entrypoint-initdb.d/90_schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dpinterview
    profiles:
      - internal_db
  fileserver:
    image: caddy:2.10.0-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "8081:8080"
      - "8082:8081"
    volumes:
      - ./site:/var/lib/filer:ro
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081/health || exit 1" ]
      start_period: 10s
      start_interval: 3s
      interval: 1m
      retries: 3
      timeout: 5s
volumes:
#  db: { }
  caddy_data: { }
  caddy_config: { }
#  static_assets: { }